### ISSUE TITLE
jakie postępy w pracy?

### ISSUE THREAD

**Issue by adan2013** [exewin/space-game#1]
Witam
Dostępny jest gdzieś w projekcie jakiś czejndżlog?

**Comment by exewin** [comment]
Hello adan2013,

A blue screen error (also called a STOP error) will appear if a problem causes your PC to shut down or restart unexpectedly.

 

For some basic steps for resolving these types of errors in Windows 10, check out the article, Troubleshoot blue screen errors. If you received this blue screen error after installing new software, hardware, or updates, and System Restore does not resolve your problem, you can also try booting to Safe Mode to uninstall whatever may have triggered the error.  To boot to Safe Mode, see Change startup settings in Windows 10.  If an update may have triggered the blue screen error, temporarily block the update from automatically installing again.

 

Most blue screen errors also include a message or error code.  If you have the error code, search for it within the support forums for more detailed information and solutions related to your specific problem.

**Comment by adan2013** [comment]
Hmmmm, I understand
Anyway I invite you to look at my project:
https://github.com/adan2013/YTMP
and
https://github.com/adan2013/WINEASIER
:)
