### ISSUE TITLE
Logo Design: Space-game

### ISSUE THREAD

**Issue by baranpirincal** [exewin/space-game#3]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by exewin** [comment]
Hi,
**That would be really great if you could make a logo.** 
I have only one suggestion: while the project on github is called 'space-game' the real game name is "Mission One" so if you're planning to add any text, please let it be "Mission One", but if you won't add any text, that's fine too :) 
If you got any questions go on.
Can't wait to see your work and thanks again.

**Comment by baranpirincal** [comment]
Hey again @exewin ,

I examined your game for a while and I made my first experiment. 

Firstly, I don't want to use any text on design because I think that, it is a game and the logo should give some clues about what will going on inside.

I want to show jet plane which we play with in game on logo design but I did not make exactly same jet and flame. I made with most basic style because  I think that maybe you can add new jets, flame appearance or etc. on your project and the jet on your logo design have to be unique and simple.

I made a jet with "M" letter form and I thought about how can we show that it is a "first game" of "MISSION" . As you can see, we can put one more layer on jet if you make it's second or third game.

Finally, don't forget it is not finished yet. I want to learn your ideas and feedbacks. We can change/add or remove something on design. I will do some arrangements anyway.

Have a nice day! :)

![mjet](https://user-images.githubusercontent.com/37786733/41280098-c855b98a-6e36-11e8-997e-76af479bacdd.png)

**Comment by exewin** [comment]
Awesome :1st_place_medal: . On the one hand these logos look very simple, but on the other hand I see that you put a lot of effort into creating them.

Ok, so I think the main concept is good. I have a few ideas for changes:

- Make the shape of jet a little taller.
- Make the flames little smaller and maybe try other shapes for them (colors are ok).
- Do some experiments with color of the jet. Grey is nice, but maybe try some variations (for example: #bba394, #7f989e).

Of course, if you think some of my requests can make logo look worse, just skip them. And thanks again :)

**Comment by baranpirincal** [comment]
@exewin 

I made jet taller. It is really better now, thank you:)

Also, I made color variations, now I am working on shape of flames.

I will put here as soon as possible.

You're welcome!

**Comment by baranpirincal** [comment]
Hey, here is the color variations and with another shape of flame:

![mjet1](https://user-images.githubusercontent.com/37786733/41325644-1b869c40-6ec4-11e8-9865-1ea416c0fc4f.png)

**Comment by baranpirincal** [comment]
Hey!

I think that, shape of jet and flame better now. I used colors which you give me it's code, and other color tones you like I thought. I am waiting your feedback for providing necessary files! :)

**Comment by exewin** [comment]
I like the 3rd (green) and 6th (brown). I'm not sure which one I will be using yet.
I think I will only need files in **.png format**. Ok, instead of just saying I've prepared a simple scheme to make things clear:
![41325644-1b869c40-6ec4-11e8-9865-1ea416c0fc4f](https://user-images.githubusercontent.com/35975175/41344873-716f43a8-6f02-11e8-87da-843e9fed6bda.png)

In total, that's 10 images.
Thanks again.

**Comment by baranpirincal** [comment]
@exewin 

You're welcome.

I uploaded all the files you wanted. It was nice to work with you!

Do not hesitate to want me to do anything, have a nice day!

Best Regards
Baran Pirinçal
Graphic Designer

![mission one first page](https://user-images.githubusercontent.com/37786733/41348322-ffa14754-6f14-11e8-9c5b-8c2455a4c8e9.jpg)

**Comment by exewin** [comment]
That's really cool. I'm also going put this huge image in project readme. 
Soon I will update credits.

New version of game (which will contain new features and logo) will be realased in a few days. I'm also thinking of showing my project to larger group, so more people can see our work.

Thank you for your time and work @baranpirincal :1st_place_medal:
